### PR TITLE
paper-badge replaced with div + css

### LINKED ISSUE #43: replace paper-badge
Paper-badge needs resize events to position itself and can't handle displaying more than 2 characters.
We currently use it to display numbers up to 2000 which doesn't work.
These kind of badges usually print things like "9+" for high numbers but I don't think we want that?

### PR DESCRIPTION
**Pull request by programmer4web**
fixes #43 
I have added an 'cosmoz-tabs-styles' module to define the 'badge' css class.
The 'badge' css class is used in tabs and tab modules.
Tests updated.
Badge css improvements.

### CODE REVIEW

**Comment by programmer4web** [comment]
@nomego I have created https://github.com/Neovici/cosmoz-tabs/issues/49 to test this in cosmoz-frontend.
Observations:
1. I have noticed that the issue about re-positioning of the badge is solved.
2. I have noticed that the background-color was different and I have updated the css to use --accent-color as paper-badge used to do.
3. Now the badge supports numbers with more then 3 characters, and the background becomes in shape of a pill.
4. Almost all css dimensions of the badge are in em. font-size: 11px; and line-height: 1;

**Comment by megheaiulian** [comment]
@dotpointer A max-width should than be decided upon.

**Comment by dotpointer** [comment]
@megheaiulian Sounds good. But here in this pull request, or maybe in another issue / pull request, because there is a need to get this pull request merged due to release demands.

**Comment by programmer4web** [comment]
@dotpointer I have added:
```
 max-width: 80px;
 text-overflow: ellipsis;
 overflow: hidden;
```

**Comment by dotpointer** [comment]
@programmer4web Good, I just tested and it works well. About 9 characters fit, then it trims down with "..." on the end.

Maybe add a mouse tooltip so to the badges which displays the whole text in the mouse tooltip when hovering the badge?

**Comment by dotpointer** [comment]
Tested again, now the tooltip is in place too.

badge

Very good, I'm satisfied.

**Pull request merged**
